apiVersion: batch/v1
kind: Job
metadata:
  name: kaniko
spec:
  template:
    spec:
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:latest
        args:
        - "--context=git://github.com/zetamin/ubuntu.git"
        - "--dockerfile=Dockerfile"
        - "--no-push"
      restartPolicy: Never
