apiVersion: batch/v1
kind: Job
metadata:
  generateName: kaniko-
spec:
  template:
    spec:
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:latest
        args:
        - "--context=${env.WORKSPACE}"
        - "--dockerfile=${env.WORKSPACE}/Dockerfile"
        - "--no-push"
        volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker/
      restartPolicy: Never